# Generated by Django 2.0.6 on 2018-10-22 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("planner", "0030_targetschool_deleted_date")]

    operations = [
        migrations.CreateModel(
            name="CommonAppTracker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField()),
                ("slug", models.SlugField(max_length=512, unique=True)),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "Tracked"),
                            (3, "International"),
                            (4, "Untracked"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="planner.School",
                    ),
                ),
            ],
        )
    ]
