# Generated by Django 2.0.6 on 2018-10-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("trackers", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="commonapptracker",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Tracked"),
                    (3, "International"),
                    (4, "Untracked"),
                    (5, "Removed"),
                ],
                default=1,
            ),
        )
    ]
