# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-28 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20161128_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matriculation_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='planner.Semester'),
        ),
    ]
