# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [("planner", "0010_audit_status")]

    operations = [
        migrations.AddField(
            model_name="school",
            name="city",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="rolling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="school",
            name="state",
            field=localflavor.us.models.USStateField(max_length=2, null=True),
        ),
    ]
