# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("planner", "0012_auto_20170130_0037")]

    operations = [
        migrations.AlterField(
            model_name="milestone",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="planner.School",
            ),
        )
    ]
