# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("planner", "0014_school_audit_notes")]

    operations = [
        migrations.AlterField(
            model_name="milestone", name="date", field=models.DateField()
        )
    ]
