# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("planner", "0015_auto_20170221_0229")]

    operations = [
        migrations.AlterModelOptions(name="student", options={"ordering": ("id",)}),
        migrations.AlterModelOptions(
            name="targetschool", options={"ordering": ("id",)}
        ),
    ]
