# Generated by Django 2.0.6 on 2018-09-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("planner", "0019_school_image")]

    operations = [
        migrations.RenameModel(
            old_name="ApplicationStatus", new_name="ApplicationSchedule"
        )
    ]
