# Generated by Django 2.0.6 on 2018-09-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("planner", "0020_auto_20180901_0315")]

    operations = [
        migrations.AddField(
            model_name="targetschool",
            name="milestones",
            field=models.ManyToManyField(to="planner.Milestone"),
        )
    ]
