# Generated by Django 2.0.6 on 2018-09-10 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("planner", "0024_audit_semester")]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.Semester"
            ),
        )
    ]
