# Generated by Django 2.0.6 on 2018-09-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("planner", "0025_auto_20180910_0003")]

    operations = [
        migrations.AddField(
            model_name="school",
            name="ipeds_id",
            field=models.CharField(
                blank=True,
                help_text="The school's IPEDS ID from the Department of Education",
                max_length=8,
                null=True,
                unique=True,
            ),
        )
    ]
