# Generated by Django 2.0.6 on 2018-09-23 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("planner", "0026_school_ipeds_id")]

    operations = [
        migrations.CreateModel(
            name="SchoolApplication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.IntegerField(
                        choices=[
                            (0, "Common App"),
                            (1, "Coalition Application"),
                            (2, "Universal College Application"),
                            (3, "School Based Application"),
                        ]
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="planner.School",
                    ),
                ),
            ],
        )
    ]
