# Generated by Django 2.0.6 on 2018-09-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("planner", "0028_targetschool_school_application")]

    operations = [
        migrations.AlterField(
            model_name="schoolapplication",
            name="application_type",
            field=models.IntegerField(
                choices=[
                    (0, "Common Application"),
                    (1, "Coalition Application"),
                    (2, "Universal College Application"),
                    (3, "School-Based Application"),
                ]
            ),
        )
    ]
