# Generated by Django 2.0.6 on 2018-09-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("planner", "0029_auto_20180928_0042")]

    operations = [
        migrations.AddField(
            model_name="targetschool",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
