# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0005_profile")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=32),
        )
    ]
