# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-26 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0007_profile_stripe_customer_id")]

    operations = [migrations.DeleteModel(name="InviteEmail")]
