# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 01:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("accounts", "0008_delete_inviteemail")]

    operations = [
        migrations.CreateModel(
            name="GoogleDriveAuth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "code",
                    models.CharField(
                        help_text="One time authorization code provided by the user",
                        max_length=64,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_drive_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
