# Generated by Django 2.0.6 on 2018-08-31 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0010_auto_20180630_0211")]

    operations = [
        migrations.RemoveField(model_name="googledriveauth", name="id_token"),
        migrations.RemoveField(model_name="googledriveauth", name="token"),
    ]
