# Generated by Django 2.0.9 on 2018-11-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0011_auto_20180831_0320")]

    operations = [
        migrations.CreateModel(
            name="ProductPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("stripe_plan_id", models.CharField(max_length=32)),
                ("trial_days", models.IntegerField(default=0)),
            ],
        )
    ]
