# Generated by Django 2.0.9 on 2018-11-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0012_productplan")]

    operations = [
        migrations.AddField(
            model_name="productplan",
            name="price",
            field=models.IntegerField(default=0, help_text="The price in cents"),
        )
    ]
