# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20161214_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.School')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='schools',
            field=models.ManyToManyField(through='planner.TargetSchool', to='planner.School'),
        ),
        migrations.AlterUniqueTogether(
            name='targetschool',
            unique_together=set([('school', 'student')]),
        ),
    ]
