# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-17 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_applicationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('ED', 'Early Decision'), ('ED II', 'Early Decision II'), ('EA', 'Early Action'), ('REA', 'Restricted Early Action'), ('RD', 'Regular Decision')], default='RD', max_length=8),
        ),
    ]
